services:
  djangoapp:
    container_name: djangoapp
    build: .
    command: >
      sh -c "
        python manage.py makemigrations api &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_HOST=db
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: {}